name: Build React Native APK

on:
  push:
    branches:
      - master # Cambia esto según la rama que desees usar

jobs:
  build:
    name: Build APK for React Native
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instalar dependencias de npm
      - name: Install dependencies
        run: npm install

      # 4. Configurar Java (necesario para Gradle)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      # 5. Configurar Android SDK
      - name: Set up Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y lib32z1 lib32stdc++6
          mkdir -p $ANDROID_HOME/cmdline-tools/latest
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools.zip -d $ANDROID_HOME/cmdline-tools/latest
          rm commandlinetools.zip
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"

      # 6. Asegurar permisos para gradlew
      - name: Ensure gradlew is executable
        run: chmod +x android/gradlew

      # 7. Construir APK
      - name: Build APK using Gradle
        run: |
          cd android
          ./gradlew assembleRelease

      # 8. Verificar el APK generado
      - name: List APK output directory
        run: ls -la android/app/build/outputs/apk/release/
