name: Build and Deploy to Itch.io

on:
  push:
    branches:
      - master # Despliegue en la rama principal

jobs:
  deploy:
    name: Build and Deploy to Itch.io
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del c贸digo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instalar dependencias y configurar entorno de React Native
      - name: Install dependencies
        run: npm install

      # 4. Configurar Java 17
      - name: Install Java 17
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      # 5. Verificar la instalaci贸n de Java
      - name: Check Java version
        run: java -version

      # 6. Instalar Android SDK y herramientas necesarias
      - name: Install Android SDK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          script: |
            sdkmanager --install "cmdline-tools;latest"
            sdkmanager --install "platform-tools"
            sdkmanager --install "platforms;android-33"

      # 7. Asegurar permisos de ejecuci贸n para gradlew
      - name: Ensure gradlew is executable
        run: chmod +x android/gradlew

      # 8. Construir el APK usando Gradle
      - name: Build APK using Gradle
        run: |
          cd android
          ./gradlew assembleRelease

      # 9. Listar el directorio de salida del APK
      - name: List APK output directory
        run: ls -la android/app/build/outputs/apk/release/

      # 10. Descargar Butler desde broth (servidor recomendado)
      - name: Download Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler

      # 11. Verificar la instalaci贸n de Butler
      - name: Butler version check
        run: ./butler -V

      # 12. Empaquetar el archivo APK generado
      - name: Prepare APK for Itch.io
        run: |
          mkdir -p debug
          cp android/app/build/outputs/apk/release/app-release.apk debug/clinicaJireh.apk

      # 13. Subir el archivo APK a Itch.io usando Butler
      - name: Push to Itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.ITCH_API_KEY }}
        run: |
          ./butler push debug/clinicaJireh.apk abelardo20200782/proyectojireh:android
