name: Build, Test, and Deploy APK to Itch.io

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy APK to Itch.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run tests units and integration
        run: |
          echo "Running tests..."
          npm test -- --ci --passWithNoTests
        env:
          CI: true

      - name: Reinstall expo-router
        run: npm install expo-router@latest

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Authenticate with Expo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas whoami

      - name: Install Java 17
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Build APK using EAS
        id: build-apk
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          eas build --platform android --profile production --non-interactive | tee build-log.txt

      - name: Extract APK URL from Logs
        id: extract-url
        run: |
          URL=$(grep -oP 'https://expo.dev/artifacts/eas/\S+\.apk' build-log.txt | tail -1)
          if [ -z "$URL" ]; then
            echo "Failed to extract APK URL from build logs."
            exit 1
          fi
          echo "APK_URL=$URL" >> $GITHUB_ENV
          echo "Found APK URL: $URL"

      - name: Download APK
        run: |
          mkdir -p debug
          curl -o debug/clinicaJireh.apk "$APK_URL"

      - name: Install Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip -d butler
          sudo mv butler/butler /usr/local/bin
          butler --version

      - name: Deploy to Itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.ITCH_API_KEY }}
        run: |
          if [ -f "debug/clinicaJireh.apk" ]; then
            echo "APK file found. Deploying to Itch.io..."
            butler push debug/clinicaJireh.apk abelardo20200782/proyectojireh:android
          else
            echo "APK file not found. Stopping deployment."
            exit 1
          fi