name: Build and Deploy APK to Itch.io

on:
  push:
    branches:
      - master # Ejecuta el workflow al realizar un push en la rama principal

jobs:
  build-and-deploy:
    name: Build and Deploy APK to Itch.io
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instalar dependencias de npm
      - name: Install dependencies
        run: npm install

      # 4. Instalar EAS CLI
      - name: Install EAS CLI
        run: npm install -g eas-cli

      # 5. Autenticar con Expo
      - name: Authenticate with Expo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas whoami

      # 6. Configurar Java 17
      - name: Install Java 17
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      # 7. Verificar la instalación de Java
      - name: Check Java version
        run: java -version

      # 8. Construir el APK usando EAS
      - name: Build APK using EAS
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform android --profile apk-release --non-interactive

      # 9. Descargar Butler desde broth (servidor recomendado)
      - name: Download Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler

      # 10. Verificar la instalación de Butler
      - name: Butler version check
        run: ./butler -V

      # 11. Preparar el archivo APK para Itch.io
      - name: Prepare APK for Itch.io
        run: |
          mkdir -p debug
          cp build/*.apk debug/clinicaJireh.apk

      # 12. Subir el archivo APK a Itch.io usando Butler
      - name: Push to Itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.ITCH_API_KEY }}
        run: |
          ./butler push debug/clinicaJireh.apk abelardo20200782/proyectojireh:android
